export const products = [
  {
    id: '1',
    name: 'Perceuse visseuse sans fil 18V',
    description: 'Perceuse visseuse sans fil professionnelle, compacte et puissante',
    longDescription: 'Cette perceuse visseuse sans fil 18V est idéale pour tous vos travaux de perçage et de vissage. Avec son moteur brushless, elle offre une puissance optimale et une longue durée de vie. Compacte et légère, elle est facile à manipuler, même dans les espaces restreints. Livrée avec deux batteries 18V, un chargeur rapide et un coffret de rangement.',
    price: 149.90,
    oldPrice: 189.90,
    discount: 21,
    image: 'https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    images: [
      'https://images.pexels.com/photos/1249611/pexels-photo-1249611.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      'https://images.pexels.com/photos/4488660/pexels-photo-4488660.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
      'https://images.pexels.com/photos/5363336/pexels-photo-5363336.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    ],
    category: 'Outils électriques',
    categoryId: 'outils',
    sku: 'OE-123456',
    inStock: true,
    isNew: true,
    isFeatured: true,
    brand: 'MaxTool',
    color: 'Noir/Jaune',
    dimensions: '20 x 8 x 22 cm',
    weight: '1.5 kg',
    warranty: '2 ans',
  },
  {
    id: '2',
    name: 'Boîte à outils complète 215 pièces',
    description: 'Ensemble d\'outils complet pour tous vos travaux de bricolage',
    price: 129.99,
    oldPrice: 159.99,
    discount: 19,
    image: 'https://images.pexels.com/photos/4195327/pexels-photo-4195327.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils manuels',
    categoryId: 'outils',
    inStock: true,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Meuleuse d\'angle 125mm 850W',
    description: 'Meuleuse puissante pour tous vos travaux de découpe et de ponçage',
    price: 59.90,
    oldPrice: 79.90,
    discount: 25,
    image: 'https://images.pexels.com/photos/5115024/pexels-photo-5115024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils électriques',
    categoryId: 'outils',
    inStock: true,
    isNew: true,
  },
  {
    id: '4',
    name: 'Échelle télescopique en aluminium 3.8m',
    description: 'Échelle extensible multi-positions, légère et robuste',
    price: 119.00,
    oldPrice: 149.00,
    discount: 20,
    image: 'https://images.pexels.com/photos/4078252/pexels-photo-4078252.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils',
    categoryId: 'outils',
    inStock: true,
  },
  {
    id: '5',
    name: 'Scie circulaire 1200W avec laser',
    description: 'Scie circulaire précise avec guidage laser et réglage de profondeur',
    price: 89.90,
    image: 'https://images.pexels.com/photos/8107199/pexels-photo-8107199.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils électriques',
    categoryId: 'outils',
    inStock: true,
    isFeatured: true,
    discount: 0,
  },
  {
    id: '6',
    name: 'Peinture murale mate blanche 10L',
    description: 'Peinture acrylique pour murs et plafonds, haute qualité et bonne couvrance',
    price: 49.90,
    image: 'https://images.pexels.com/photos/5586321/pexels-photo-5586321.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Peinture',
    categoryId: 'peinture',
    inStock: true,
    isNew: false,
    discount: 0,
  },
  {
    id: '7',
    name: 'Tournevis électrique sans fil 3.6V',
    description: 'Tournevis compact avec batterie lithium-ion et éclairage LED',
    price: 29.90,
    oldPrice: 39.90,
    discount: 25,
    image: 'https://images.pexels.com/photos/5733621/pexels-photo-5733621.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils électriques',
    categoryId: 'outils',
    inStock: true,
    isNew: true,
  },
  {
    id: '8',
    name: 'Kit de jardinage 12 pièces',
    description: 'Ensemble d\'outils de jardinage avec sac de rangement',
    price: 34.90,
    image: 'https://images.pexels.com/photos/296230/pexels-photo-296230.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Jardin',
    categoryId: 'jardin',
    inStock: true,
    isFeatured: true,
    discount: 0,
  },
  {
    id: '9',
    name: 'Robinet mitigeur de cuisine chromé',
    description: 'Robinet mitigeur design avec douchette extractible',
    price: 79.90,
    oldPrice: 99.90,
    discount: 20,
    image: 'https://images.pexels.com/photos/1454805/pexels-photo-1454805.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Plomberie',
    categoryId: 'plomberie',
    inStock: true,
  },
  {
    id: '10',
    name: 'Ensemble de clés à douille 1/4" et 1/2"',
    description: 'Coffret de 94 clés à douille et accessoires en chrome vanadium',
    price: 69.90,
    oldPrice: 89.90,
    discount: 22,
    image: 'https://images.pexels.com/photos/1027508/pexels-photo-1027508.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils manuels',
    categoryId: 'outils',
    inStock: true,
    isFeatured: true,
  },
  {
    id: '11',
    name: 'Ponceuse excentrique 300W',
    description: 'Ponceuse ergonomique avec système d\'aspiration et variateur de vitesse',
    price: 54.90,
    image: 'https://images.pexels.com/photos/3822843/pexels-photo-3822843.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils électriques',
    categoryId: 'outils',
    inStock: true,
    discount: 0,
  },
  {
    id: '12',
    name: 'Projecteur LED 50W avec détecteur',
    description: 'Projecteur extérieur étanche IP65 avec détecteur de mouvement',
    price: 39.90,
    oldPrice: 49.90,
    discount: 20,
    image: 'https://images.pexels.com/photos/194096/pexels-photo-194096.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Électricité',
    categoryId: 'electricite',
    inStock: true,
    isNew: true,
  },
  {
    id: '13',
    name: 'Salon de jardin en résine tressée',
    description: 'Ensemble table et 4 fauteuils en résine tressée et aluminium',
    price: 349.90,
    oldPrice: 449.90,
    discount: 22,
    image: 'https://images.pexels.com/photos/279835/pexels-photo-279835.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Jardin',
    categoryId: 'jardin',
    inStock: true,
    isFeatured: true,
  },
  {
    id: '14',
    name: 'Kit douche à l\'italienne',
    description: 'Kit complet pour réaliser une douche à l\'italienne',
    price: 189.90,
    image: 'https://images.pexels.com/photos/7538022/pexels-photo-7538022.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Plomberie',
    categoryId: 'plomberie',
    inStock: true,
    discount: 0,
  },
  {
    id: '15',
    name: 'Marteau de charpentier 450g',
    description: 'Marteau professionnel avec manche ergonomique anti-vibrations',
    price: 14.90,
    image: 'https://images.pexels.com/photos/209235/pexels-photo-209235.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Outils manuels',
    categoryId: 'outils',
    inStock: true,
    discount: 0,
  },
  {
    id: '16',
    name: 'Tuyau d\'arrosage extensible 30m',
    description: 'Tuyau d\'arrosage qui s\'allonge sous pression d\'eau',
    price: 29.90,
    oldPrice: 39.90,
    discount: 25,
    image: 'https://images.pexels.com/photos/2252584/pexels-photo-2252584.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Jardin',
    categoryId: 'jardin',
    inStock: true,
    isNew: true,
  },
];
